apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-bos-dr-stub.name" . }}-wiremock-certs-secret
  labels:
  {{- include "eric-bos-dr-stub.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-bos-dr-stub.annotations" . | nindent 4 }}
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "certs/*.p12" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}