apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-bos-dr-stub.name" . }}-wiremock
  labels:
  {{- include "eric-bos-dr-stub.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-bos-dr-stub.annotations" . | nindent 4 }}
spec:
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily | quote }}]
  {{- end }}
  {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http-api
    - protocol: TCP
      port: 443
      targetPort: 8443
      name: https-api
  selector:
    app: {{ include "eric-bos-dr-stub.name" . }}-wiremock