#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-bos-dr-stub.name" . }}-sa
  labels:
  {{- include "eric-bos-dr-stub.labels" .| nindent 4 }}
  annotations:
  {{- include "eric-bos-dr-stub.annotations" .| nindent 4 }}
automountServiceAccountToken: false
